import { app, BrowserWindow, globalShortcut, ipcMain, clipboard, nativeImage, screen, Tray, Menu, systemPreferences, dialog, shell } from 'electron'
import { join, dirname } from 'path'
import { fileURLToPath, pathToFileURL } from 'url'
import { exec, execSync } from 'child_process'
import { existsSync, mkdirSync, unlinkSync, writeFileSync } from 'fs'
import { v4 as uuidv4 } from 'uuid'
import Store from 'electron-store'
import type { ClipboardItem, Settings } from '../common/types'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

// Default pasteboard types to ignore (matches Maccy's approach)
const DEFAULT_IGNORED_TYPES = [
  // Always ignored - transient/confidential types
  'org.nspasteboard.TransientType',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
  // Password managers and secure apps
  'com.agilebits.onepassword',
  'com.typeit4me.clipping',
  'de.petermaurer.TransientPasteboardType',
  'Pasteboard generator type',
  'net.antelle.keeweb'
]

const defaultSettings: Settings = {
  historyLimit: 500,
  pollingInterval: 500,
  launchAtLogin: false,
  clearOnQuit: false,
  showInDock: false,
  hotkey: 'Option+Space',
  playSoundOnCopy: false,
  ignoreDuplicates: true,
  ignorePasswordManagers: true,
  ignoredPasteboardTypes: DEFAULT_IGNORED_TYPES,
  panelPosition: 'bottom',
  language: 'en',
  pasteDirectly: false, // Default: copy only (user manually pastes)
  cardSize: 'medium',
  loadFavicons: false,
  // 8MB default; images larger than this will be downscaled before persisting.
  maxImageBytes: 8 * 1024 * 1024
}

const store = new Store<{ history: ClipboardItem[], settings: Settings }>({
  defaults: {
    history: [],
    settings: defaultSettings
  }
})

// In-memory cache so we can debounce disk writes without losing consistency.
let historyCache: ClipboardItem[] = store.get('history')
let pendingHistorySave: ReturnType<typeof setTimeout> | null = null

function getImagesDir(): string {
  const dir = join(app.getPath('userData'), 'images')
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }
  return dir
}

function deleteImageFileForItem(item: ClipboardItem) {
  if (item.type !== 'image') return
  const imagePath = item.metadata.imagePath
  if (!imagePath) return
  try {
    if (existsSync(imagePath)) unlinkSync(imagePath)
  } catch (e) {
    console.warn('Failed to delete image file:', imagePath, e)
  }
}

function applyHistoryUpdate(next: ClipboardItem[]) {
  // Cleanup removed image files (best-effort)
  const previousPaths = new Set(
    historyCache
      .filter(i => i.type === 'image' && i.metadata.imagePath)
      .map(i => i.metadata.imagePath as string)
  )
  const nextPaths = new Set(
    next
      .filter(i => i.type === 'image' && i.metadata.imagePath)
      .map(i => i.metadata.imagePath as string)
  )
  for (const p of previousPaths) {
    if (!nextPaths.has(p)) {
      try {
        if (existsSync(p)) unlinkSync(p)
      } catch {
        // ignore
      }
    }
  }

  // Play sound when a new item is captured (list grew)
  if (next.length > historyCache.length) {
    const settings = getSettings()
    if (settings.playSoundOnCopy) {
      exec('afplay /System/Library/Sounds/Tink.aiff')
    }
  }

  historyCache = next
  mainWindow?.webContents.send('history-updated', historyCache)

  // PERFORMANCE: debounce disk writes to reduce electron-store churn.
  if (pendingHistorySave) clearTimeout(pendingHistorySave)
  pendingHistorySave = setTimeout(() => {
    store.set('history', historyCache)
    pendingHistorySave = null
  }, 1000)
}

function persistImageToDisk(id: string, img: import('electron').NativeImage, settings: Settings) {
  let toSave = img
  let buffer = toSave.toPNG()
  let mime = 'image/png'
  let ext = 'png'

  if (buffer.byteLength > settings.maxImageBytes) {
    const size = toSave.getSize()
    const targetWidth = Math.min(1600, size.width)
    toSave = toSave.resize({ width: targetWidth })
    buffer = toSave.toPNG()
  }
  if (buffer.byteLength > settings.maxImageBytes) {
    buffer = toSave.toJPEG(80)
    mime = 'image/jpeg'
    ext = 'jpg'
  }

  const imagePath = join(getImagesDir(), `${id}.${ext}`)
  writeFileSync(imagePath, buffer)
  return { imagePath, fileUrl: pathToFileURL(imagePath).toString(), mime }
}

function migrateHistoryImagesToDisk() {
  const settings = getSettings()
  let changed = false

  const migrated = historyCache.map(item => {
    if (item.type !== 'image') return item
    if (item.metadata.imagePath && existsSync(item.metadata.imagePath)) return item
    if (!item.content.startsWith('data:')) return item

    try {
      const img = nativeImage.createFromDataURL(item.content)
      if (img.isEmpty()) return item
      const persisted = persistImageToDisk(item.id, img, settings)
      changed = true
      return {
        ...item,
        content: persisted.fileUrl,
        metadata: {
          ...item.metadata,
          imagePath: persisted.imagePath,
          imageMime: persisted.mime
        }
      }
    } catch {
      return item
    }
  })

  if (changed) {
    historyCache = migrated
    store.set('history', historyCache)
  }
}

let mainWindow: BrowserWindow | null = null
let settingsWindow: BrowserWindow | null = null
let tray: Tray | null = null
let lastClipboardContent = ''
let clipboardPollInterval: ReturnType<typeof setInterval> | null = null
let previousApp = '' // Store the app that was active before opening clipboard panel

function hideMainWindow() {
  if (!mainWindow) return
  if (!mainWindow.isVisible()) return
  // Keep renderer state in sync (used for clearing search/selection, etc.)
  mainWindow.webContents.send('panel-hidden')
  mainWindow.hide()
}

// In-memory settings cache — avoids hitting disk (electron-store) on every
// clipboard poll cycle. Invalidated only when settings are saved.
let _settingsCache: Settings | null = null

function getSettings(): Settings {
  if (_settingsCache) return _settingsCache
  _settingsCache = store.get('settings') || defaultSettings
  return _settingsCache
}

function invalidateSettingsCache() {
  _settingsCache = null
}

function getWindowBounds() {
  // Get display where cursor is (for multi-monitor support)
  const cursorPoint = screen.getCursorScreenPoint()
  const display = screen.getDisplayNearestPoint(cursorPoint)
  const { x: displayX, y: displayY, width, height } = display.bounds

  const settings = getSettings()
  const panelSize = 320

  switch (settings.panelPosition) {
    case 'top':
      return { width, height: panelSize, x: displayX, y: displayY }
    case 'left':
      return { width: panelSize, height, x: displayX, y: displayY }
    case 'right':
      return { width: panelSize, height, x: displayX + width - panelSize, y: displayY }
    case 'bottom':
    default:
      return { width, height: panelSize, x: displayX, y: displayY + height - panelSize }
  }
}

function configureExternalLinkHandling(win: BrowserWindow) {
  // SECURITY: never allow renderer-created windows (window.open/target=_blank)
  // to create new BrowserWindows. Open approved URLs externally instead.
  win.webContents.setWindowOpenHandler(({ url }) => {
    // Best-effort open externally; also enforce protocol allowlist.
    try {
      const parsed = new URL(url)
      const allowed = ['http:', 'https:', 'mailto:']
      if (allowed.includes(parsed.protocol)) {
        shell.openExternal(url)
      }
    } catch {
      // ignore invalid URLs
    }

    return { action: 'deny' }
  })
}

function createWindow() {
  const bounds = getWindowBounds()

  mainWindow = new BrowserWindow({
    ...bounds,
    frame: false,
    transparent: true,
    vibrancy: 'under-window',
    visualEffectState: 'active',
    alwaysOnTop: true,
    skipTaskbar: true,
    resizable: false,
    show: false,
    webPreferences: {
      preload: join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false
    }
  })

  configureExternalLinkHandling(mainWindow)

  const url = process.env.VITE_DEV_SERVER_URL
  if (url) {
    console.log('Loading dev URL:', url)
    mainWindow.loadURL(url)
    mainWindow.webContents.openDevTools({ mode: 'detach' })
  } else {
    mainWindow.loadFile(join(__dirname, '../dist/index.html'))
  }

  mainWindow.webContents.on('did-finish-load', () => {
    console.log('Window content loaded')
  })

  mainWindow.webContents.on('did-fail-load', (_, code, desc) => {
    console.error('Failed to load:', code, desc)
  })

  mainWindow.on('blur', () => {
    if (mainWindow?.isVisible()) {
      hideMainWindow()
    }
  })
}

function createTray() {
  // Try multiple paths for the tray icon
  const possiblePaths = [
    join(__dirname, '../assets/trayTemplate.png'),  // Dev mode
    join(process.resourcesPath, 'assets/trayTemplate.png'),  // Production (extraResources)
    join(__dirname, 'assets/trayTemplate.png'),  // Alternative
  ]

  let icon = nativeImage.createEmpty()
  for (const iconPath of possiblePaths) {
    console.log('Trying tray icon path:', iconPath)
    const testIcon = nativeImage.createFromPath(iconPath)
    if (!testIcon.isEmpty()) {
      icon = testIcon
      console.log('Loaded tray icon from:', iconPath)
      break
    }
  }

  icon.setTemplateImage(true)

  if (icon.isEmpty()) {
    console.error('Failed to load tray icon from any path, using fallback')
    const fallback = nativeImage.createFromDataURL(
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMklEQVQ4T2NkIBMwkqmegXKDGRhggOL/DAwMjMRoHjUAl7cHiw8YRsMRNkcPltBgoCYHAHCbBBHpOpp5AAAAAElFTkSuQmCC'
    )
    fallback.setTemplateImage(true)
    tray = new Tray(fallback)
  } else {
    tray = new Tray(icon)
  }
  tray.setToolTip('SimpleMacClipboardManager')

  updateTrayMenu()
  tray.on('click', toggleWindow)

  console.log('Tray icon created')
}

function updateTrayMenu() {
  if (!tray) return

  const menu = Menu.buildFromTemplate([
    { label: 'Show Clipboard (⌥Space)', click: () => toggleWindow() },
    { type: 'separator' },
    { label: 'Settings...', click: () => openSettings() },
    { label: 'How to Use...', click: () => showHelp() },
    { label: 'About...', click: () => showAbout() },
    { type: 'separator' },
    { label: 'Clear History', click: () => clearHistory() },
    { type: 'separator' },
    { label: 'Quit', click: () => app.quit() }
  ])

  tray.setContextMenu(menu)
}

function openSettings() {
  if (settingsWindow) {
    settingsWindow.focus()
    return
  }

  settingsWindow = new BrowserWindow({
    width: 480,
    height: 700,
    title: 'Settings',
    resizable: false,
    minimizable: false,
    maximizable: false,
    fullscreenable: false,
    show: false,
    backgroundColor: '#2a2a2a',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false
    }
  })

  configureExternalLinkHandling(settingsWindow)

  const url = process.env.VITE_DEV_SERVER_URL
  if (url) {
    settingsWindow.loadURL(url + '#settings')
  } else {
    settingsWindow.loadFile(join(__dirname, '../dist/index.html'), { hash: 'settings' })
  }

  settingsWindow.once('ready-to-show', () => {
    settingsWindow?.show()
  })

  settingsWindow.on('closed', () => {
    settingsWindow = null
  })
}

function toggleWindow() {
  if (!mainWindow) return

  if (mainWindow.isVisible()) {
    hideMainWindow()
  } else {
    // Remember which app was active before opening the panel
    try {
      const script = 'tell application "System Events" to get name of first application process whose frontmost is true'
      previousApp = execSync(`osascript -e '${script}'`, { encoding: 'utf8', timeout: 500 }).trim()
      console.log('Previous app:', previousApp)
    } catch (e) {
      previousApp = ''
    }

    const bounds = getWindowBounds()
    mainWindow.setBounds(bounds)
    mainWindow.show()
    mainWindow.focus()
    mainWindow.webContents.send('panel-shown')
  }
}

function clearHistory() {
  // Remove any persisted image files before clearing.
  for (const item of historyCache) deleteImageFileForItem(item)
  historyCache = []
  store.set('history', [])
  mainWindow?.webContents.send('history-updated', [])
}

// Move an item to the top of history (when pasted/copied from our app)
function moveItemToTop(id: string) {
  const itemIndex = historyCache.findIndex(h => h.id === id)
  if (itemIndex > 0) {
    const item = historyCache[itemIndex]
    item.createdAt = Date.now() // Update timestamp
    const updated = [item, ...historyCache.filter(h => h.id !== id)]
    // Re-sort: pinned items first, then by createdAt
    updated.sort((a, b) => {
      if (a.pinned && !b.pinned) return -1
      if (!a.pinned && b.pinned) return 1
      return b.createdAt - a.createdAt
    })
    applyHistoryUpdate(updated)
  }
}

function showHelp() {
  const iconPath = app.isPackaged
    ? join(process.resourcesPath, 'assets', 'logo.jpg')
    : join(__dirname, '..', 'assets', 'logo.jpg')

  dialog.showMessageBox({
    type: 'info',
    icon: nativeImage.createFromPath(iconPath),
    title: 'How to Use',
    message: 'SimpleMacClipboardManager',
    detail: `Keyboard Shortcuts:
• ⌥Space - Open/close clipboard panel
• ←→ or ↑↓ - Navigate between items
• Enter - Copy to clipboard (or paste if enabled)
• ⌘C - Copy to clipboard (always)
• ⇧Enter - Paste directly as plain text
• Space - Quick Look preview
• ⌘1-9 - Quick paste items 1-9
• ⌘⌫ - Delete selected item
• Esc - Close panel

Mouse Actions:
• Click - Select item
• Double-click - Copy (or paste if enabled)
• Right-click - Copy (or paste if enabled)
• Star icon - Pin/unpin item

Tips:
• Type to search clipboard history
• Use filter buttons to show specific types
• Pinned items stay at the top
• Enable "Paste directly" in Settings to auto-paste`,
    buttons: ['OK']
  })
}

function showAbout() {
  const iconPath = app.isPackaged
    ? join(process.resourcesPath, 'assets', 'logo.jpg')
    : join(__dirname, '..', 'assets', 'logo.jpg')

  const version = app.getVersion()

  // Show the main window briefly so the dialog has a parent and doesn't get
  // lost behind other windows (which makes macOS appear to hang).
  if (mainWindow && !mainWindow.isVisible()) {
    mainWindow.showInactive()
  }

  dialog.showMessageBox(mainWindow!, {
    type: 'info',
    icon: nativeImage.createFromPath(iconPath),
    title: 'About',
    message: 'SimpleMacClipboardManager',
    detail: `Version ${version}

A free, lightweight clipboard manager for macOS.
Keep your clipboard history organized and accessible.

Created by @robbyczgw-cla`,
    buttons: ['GitHub Repo', 'Author Profile', 'OK'],
    defaultId: 2,
    cancelId: 2
  }).then(result => {
    if (result.response === 0) {
      shell.openExternal('https://github.com/robbyczgw-cla/SimpleMacClipboardManager')
    } else if (result.response === 1) {
      shell.openExternal('https://github.com/robbyczgw-cla')
    }
  })
}

function detectContentType(text: string): ClipboardItem['type'] {
  const trimmed = text.trim()
  if (/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/.test(trimmed)) return 'color'
  if (/^https?:\/\/\S+$/.test(trimmed)) return 'link'
  if (/^(\/|~\/|[A-Z]:\\)/.test(trimmed)) return 'file'
  return 'text'
}

// Activate a previously focused app and simulate Cmd+V.
// Sanitizes the app name to prevent shell/AppleScript injection.
function activateAndPaste(appName: string) {
  setTimeout(() => {
    try {
      if (appName) {
        // Escape backslashes and double-quotes to prevent AppleScript injection
        const safe = appName.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
        execSync(`osascript -e 'tell application "${safe}" to activate' -e 'delay 0.1' -e 'tell application "System Events" to keystroke "v" using command down'`)
      }
    } catch (e) {
      console.error('Failed to simulate paste:', e)
    }
  }, 100)
}

// Get favicon URL for a domain using Google's service
function getFaviconUrl(url: string): string {
  try {
    const domain = new URL(url).hostname
    return `https://www.google.com/s2/favicons?domain=${domain}&sz=32`
  } catch {
    return ''
  }
}

// Password manager app identifiers (backup check by app name)
const PASSWORD_MANAGER_APPS = [
  '1password', 'onepassword', 'bitwarden', 'lastpass', 'dashlane',
  'keeper', 'keychain', 'enpass', 'roboform', 'nordpass', 'proton pass'
]

// Cache the frontmost app result to avoid spawning osascript on every poll cycle.
// The cache TTL (2s) is short enough to stay accurate but long enough to cut
// osascript invocations by ~4x at the default 500ms polling interval.
let _frontmostAppCache = ''
let _frontmostAppCacheTime = 0
const FRONTMOST_APP_CACHE_TTL = 2000

function getFrontmostApp(): string {
  const now = Date.now()
  if (now - _frontmostAppCacheTime < FRONTMOST_APP_CACHE_TTL) {
    return _frontmostAppCache
  }
  try {
    const script = 'tell application "System Events" to get name of first application process whose frontmost is true'
    const result = execSync(`osascript -e '${script}'`, { encoding: 'utf8', timeout: 500 })
    _frontmostAppCache = result.trim().toLowerCase()
  } catch {
    _frontmostAppCache = ''
  }
  _frontmostAppCacheTime = now
  return _frontmostAppCache
}

// Check if clipboard contains ignored pasteboard types (Maccy-style)
function hasIgnoredPasteboardType(): boolean {
  const settings = getSettings()
  const ignoredTypes = settings.ignoredPasteboardTypes || DEFAULT_IGNORED_TYPES

  try {
    const formats = clipboard.availableFormats()
    return formats.some(format =>
      ignoredTypes.some(ignored =>
        format.toLowerCase().includes(ignored.toLowerCase())
      )
    )
  } catch {
    return false
  }
}

function isPasswordManagerActive(): boolean {
  // First check pasteboard types (more reliable)
  if (hasIgnoredPasteboardType()) {
    return true
  }
  // Fallback to app name check
  const frontApp = getFrontmostApp()
  return PASSWORD_MANAGER_APPS.some(pm => frontApp.includes(pm))
}

function startClipboardPolling() {
  const settings = getSettings()

  if (clipboardPollInterval) {
    clearInterval(clipboardPollInterval)
  }

  // Safely read initial clipboard content
  try {
    lastClipboardContent = clipboard.readText() || ''
  } catch (e) {
    console.error('Failed to read initial clipboard:', e)
    lastClipboardContent = ''
  }

  clipboardPollInterval = setInterval(pollClipboard, settings.pollingInterval)
  console.log('Clipboard polling started with interval:', settings.pollingInterval)
}

// Track last image by bitmap size + byte-length — far cheaper than toDataURL()
// which performs a full PNG encode on every poll cycle.
let lastImageBitmapKey = ''

function getImageBitmapKey(image: Electron.NativeImage): string {
  const size = image.getSize()
  const bitmap = image.getBitmap()
  return `${size.width}x${size.height}:${bitmap.byteLength}`
}

function pollClipboard() {
  try {
    const settings = getSettings()

    // --- Text check first (very cheap: string comparison) ---
    const text = clipboard.readText()

    if (text && text !== lastClipboardContent) {
      // Text changed — check password manager once, then process
      if (settings.ignorePasswordManagers && isPasswordManagerActive()) {
        console.log('Ignored clipboard from password manager')
        lastClipboardContent = text
        return
      }

      if (settings.ignoreDuplicates && historyCache.length > 0 && historyCache[0].content === text) {
        lastClipboardContent = text
        return
      }

      lastClipboardContent = text
      lastImageBitmapKey = '' // Clear image when text is copied
      const type = detectContentType(text)
      const sourceApp = getFrontmostApp()

      const MAX_SEARCH_TEXT = 5000
      const searchText = text.length > MAX_SEARCH_TEXT
        ? text.slice(0, MAX_SEARCH_TEXT).toLowerCase()
        : text.toLowerCase()

      const item: ClipboardItem = {
        id: uuidv4(),
        type,
        content: text,
        metadata: {
          url: type === 'link' ? text : undefined,
          colorHex: type === 'color' ? text : undefined,
          sourceApp: sourceApp || undefined,
          favicon: type === 'link' && settings.loadFavicons ? getFaviconUrl(text) : undefined
        },
        createdAt: Date.now(),
        searchText,
        pinned: false
      }

      const filtered = historyCache.filter(h => h.content !== text)
      const updated = [item, ...filtered].slice(0, settings.historyLimit)
      applyHistoryUpdate(updated)
      return
    }

    // --- Image check (only if text didn't change) ---
    // clipboard.readImage() is expensive; we skip it when text already changed.
    const image = clipboard.readImage()

    if (!image.isEmpty()) {
      // Use bitmap dimensions + byte-length for change detection instead of
      // toDataURL() which does a full PNG encode every cycle.
      const bitmapKey = getImageBitmapKey(image)

      if (bitmapKey !== lastImageBitmapKey && bitmapKey !== '0x0:0') {
        lastImageBitmapKey = bitmapKey

        if (settings.ignorePasswordManagers && isPasswordManagerActive()) {
          return
        }

        const sourceApp = getFrontmostApp()
        const id = uuidv4()

        const thumbImg = image.resize({ width: 120, height: 120 })
        const thumbnail = thumbImg.toJPEG(70).toString('base64')
        const thumbnailDataUrl = `data:image/jpeg;base64,${thumbnail}`

        let persisted: ReturnType<typeof persistImageToDisk>
        try {
          persisted = persistImageToDisk(id, image, settings)
        } catch (e) {
          console.error('Failed to persist image file:', e)
          return
        }

        const item: ClipboardItem = {
          id,
          type: 'image',
          content: persisted.fileUrl,
          thumbnail: thumbnailDataUrl,
          metadata: {
            sourceApp: sourceApp || undefined,
            imagePath: persisted.imagePath,
            imageMime: persisted.mime
          },
          createdAt: Date.now(),
          searchText: 'image screenshot',
          pinned: false
        }

        const updated = [item, ...historyCache].slice(0, settings.historyLimit)
        applyHistoryUpdate(updated)
      }
    }
  } catch (e) {
    console.error('Clipboard poll error:', e)
  }
}

function applySettings(settings: Settings) {
  // Apply launch at login
  app.setLoginItemSettings({
    openAtLogin: settings.launchAtLogin,
    openAsHidden: true
  })

  // Apply dock visibility
  if (settings.showInDock) {
    app.dock?.show()
  } else {
    app.dock?.hide()
  }

  // Restart polling with new interval
  startClipboardPolling()

  // Re-register hotkey if changed
  globalShortcut.unregisterAll()
  const hotkeyRegistered = globalShortcut.register(settings.hotkey, toggleWindow)
  console.log('Hotkey re-registered:', settings.hotkey, hotkeyRegistered)

  // Update window position if panel position changed
  if (mainWindow && !mainWindow.isVisible()) {
    const bounds = getWindowBounds()
    mainWindow.setBounds(bounds)
  }
}

app.whenReady().then(() => {
  console.log('App ready, creating window and tray...')

  // Accessibility permission is not actually required for Electron's globalShortcut
  // API, so we just log the status without prompting. The dialog was shown on every
  // fresh install/re-sign and confused users since hotkeys worked regardless.
  if (process.platform === 'darwin') {
    const isTrusted = systemPreferences.isTrustedAccessibilityClient(false)
    console.log('Accessibility permission:', isTrusted ? 'granted' : 'not granted')
  }

  const settings = getSettings()

  // Migration: older versions stored full image data URLs in electron-store.
  // Convert them to on-disk files to reduce storage and memory usage.
  migrateHistoryImagesToDisk()

  // Apply initial settings
  if (!settings.showInDock) {
    app.dock?.hide()
  }

  app.setLoginItemSettings({
    openAtLogin: settings.launchAtLogin,
    openAsHidden: true
  })

  createWindow()
  createTray()
  startClipboardPolling()

  // Register hotkey
  const registered = globalShortcut.register(settings.hotkey, toggleWindow)
  console.log('Hotkey registered:', registered)

  // IPC handlers
  ipcMain.handle('get-history', () => historyCache)

  // SECURITY: renderer requests to open external links should go through main.
  ipcMain.handle('open-external', async (_evt, url: string) => {
    try {
      const parsed = new URL(url)
      const allowed = ['http:', 'https:', 'mailto:']
      if (!allowed.includes(parsed.protocol)) return { success: false }
      await shell.openExternal(url)
      return { success: true }
    } catch {
      return { success: false }
    }
  })

  ipcMain.handle('get-image-drag-path', async (_evt, item: ClipboardItem) => {
    try {
      if (item.type !== 'image') return { success: false }

      if (item.metadata.imagePath && existsSync(item.metadata.imagePath)) {
        return {
          success: true,
          path: pathToFileURL(item.metadata.imagePath).toString(),
          mime: item.metadata.imageMime || 'image/png',
          filename: `clipboard-${item.id}`
        }
      }

      if (item.content.startsWith('data:')) {
        const img = nativeImage.createFromDataURL(item.content)
        if (img.isEmpty()) return { success: false }
        const settings = getSettings()
        const persisted = persistImageToDisk(item.id, img, settings)
        // Do not modify history here; this is just for drag-and-drop.
        return {
          success: true,
          path: persisted.fileUrl,
          mime: persisted.mime,
          filename: `clipboard-${item.id}`
        }
      }

      return { success: false }
    } catch {
      return { success: false }
    }
  })
  ipcMain.handle('paste-item', (_, item: ClipboardItem) => {
    if (item.type === 'image') {
      // For images, write the image to clipboard (file-based preferred).
      const img = item.metadata.imagePath
        ? nativeImage.createFromPath(item.metadata.imagePath)
        : (item.content.startsWith('data:') ? nativeImage.createFromDataURL(item.content) : nativeImage.createEmpty())
      if (!img.isEmpty()) clipboard.writeImage(img)
    } else {
      clipboard.writeText(item.content)
    }
    lastClipboardContent = item.content
    lastImageBitmapKey = ''

    // Move item to top of history (update timestamp)
    moveItemToTop(item.id)

    hideMainWindow()

    // Activate the previous app and simulate Cmd+V
    activateAndPaste(previousApp)
  })

  ipcMain.handle('paste-plain', (_, item: ClipboardItem) => {
    // Paste as plain text. Most clipboard content we capture is already plain text,
    // but we keep this handler for explicit "paste without formatting" requests.
    const plainText = item.type === 'image' ? '[Image]' : item.content
    clipboard.writeText(plainText)
    lastClipboardContent = plainText

    // Move item to top of history (update timestamp)
    moveItemToTop(item.id)

    hideMainWindow()

    // Activate the previous app and simulate Cmd+V
    activateAndPaste(previousApp)
  })

  ipcMain.handle('copy-only', (_, item: ClipboardItem) => {
    // Copy to clipboard without auto-pasting
    if (item.type === 'image') {
      const img = item.metadata.imagePath
        ? nativeImage.createFromPath(item.metadata.imagePath)
        : (item.content.startsWith('data:') ? nativeImage.createFromDataURL(item.content) : nativeImage.createEmpty())
      if (!img.isEmpty()) clipboard.writeImage(img)
    } else {
      clipboard.writeText(item.content)
    }
    lastClipboardContent = item.content
    lastImageBitmapKey = ''

    // Move item to top of history (update timestamp)
    moveItemToTop(item.id)

    hideMainWindow()
    // No auto-paste - user will manually Cmd+V
  })

  // Copy text to clipboard from renderer (e.g. merge paste) while updating
  // lastClipboardContent so the poller doesn't re-capture it as a new item.
  ipcMain.handle('copy-text', (_, text: string) => {
    clipboard.writeText(text)
    lastClipboardContent = text
  })

  ipcMain.handle('delete-item', (_, id: string) => {
    const toDelete = historyCache.find(h => h.id === id)
    if (toDelete) deleteImageFileForItem(toDelete)

    const history = historyCache.filter(h => h.id !== id)
    applyHistoryUpdate(history)
  })

  ipcMain.handle('toggle-pin', (_, id: string) => {
    const history = historyCache.map(h =>
      h.id === id ? { ...h, pinned: !h.pinned } : h
    )
    // Sort: pinned items first, then by createdAt
    history.sort((a, b) => {
      if (a.pinned && !b.pinned) return -1
      if (!a.pinned && b.pinned) return 1
      if (!a.pinned && !b.pinned) return b.createdAt - a.createdAt
      return b.createdAt - a.createdAt
    })
    applyHistoryUpdate(history)
  })

  ipcMain.handle('clear-history', clearHistory)
  ipcMain.handle('hide-window', () => hideMainWindow())

  // Settings handlers
  ipcMain.handle('get-settings', () => getSettings())

  ipcMain.handle('save-settings', (_, newSettings: Settings) => {
    store.set('settings', newSettings)
    invalidateSettingsCache()
    applySettings(newSettings)
    console.log('Settings saved:', newSettings)
  })

  ipcMain.handle('open-settings', openSettings)

  // Export history as JSON
  ipcMain.handle('export-history', async () => {
    const history = historyCache
    const result = await dialog.showSaveDialog({
      title: 'Export Clipboard History',
      defaultPath: `clipboard-history-${new Date().toISOString().split('T')[0]}.json`,
      filters: [{ name: 'JSON', extensions: ['json'] }]
    })

    if (!result.canceled && result.filePath) {
      const fs = await import('fs')
      fs.writeFileSync(result.filePath, JSON.stringify(history, null, 2))
      return { success: true, path: result.filePath }
    }
    return { success: false }
  })

  // Import history from JSON
  ipcMain.handle('import-history', async () => {
    const result = await dialog.showOpenDialog({
      title: 'Import Clipboard History',
      filters: [{ name: 'JSON', extensions: ['json'] }],
      properties: ['openFile']
    })

    if (!result.canceled && result.filePaths.length > 0) {
      try {
        const fs = await import('fs')
        const data = fs.readFileSync(result.filePaths[0], 'utf8')
        const imported = JSON.parse(data) as ClipboardItem[]
        const settings = getSettings()

        // Merge with existing history, avoiding duplicates by content
        const existing = historyCache
        const existingContents = new Set(existing.map(h => h.content))
        const newItems = imported.filter(item => !existingContents.has(item.content))

        const merged = [...existing, ...newItems].slice(0, settings.historyLimit)
        // Sort: pinned first, then by date
        merged.sort((a, b) => {
          if (a.pinned && !b.pinned) return -1
          if (!a.pinned && b.pinned) return 1
          return b.createdAt - a.createdAt
        })

        applyHistoryUpdate(merged)
        return { success: true, count: newItems.length }
      } catch (e) {
        return { success: false, error: 'Invalid JSON file' }
      }
    }
    return { success: false }
  })

  console.log('All handlers registered')
})

app.on('will-quit', () => {
  // Flush any pending debounced history write so data isn't lost on quit
  if (pendingHistorySave) {
    clearTimeout(pendingHistorySave)
    pendingHistorySave = null
    store.set('history', historyCache)
  }

  const settings = getSettings()

  // Clear history on quit if enabled
  if (settings.clearOnQuit) {
    for (const item of historyCache) deleteImageFileForItem(item)
    historyCache = []
    store.set('history', [])
    console.log('History cleared on quit')
  }

  globalShortcut.unregisterAll()
  if (clipboardPollInterval) clearInterval(clipboardPollInterval)
})

app.on('window-all-closed', (e: Event) => {
  e.preventDefault() // Keep app running
})
