import { app, BrowserWindow, globalShortcut, ipcMain, clipboard, nativeImage, screen, Tray, Menu, systemPreferences, dialog, shell } from 'electron'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'
import { v4 as uuidv4 } from 'uuid'
import Store from 'electron-store'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

interface ClipboardItem {
  id: string
  type: 'text' | 'image' | 'link' | 'file' | 'color'
  content: string
  thumbnail?: string
  metadata: {
    url?: string
    colorHex?: string
    sourceApp?: string
    favicon?: string // Favicon URL for links
    title?: string   // Page title for links
  }
  createdAt: number
  searchText: string
  pinned?: boolean
}

type PanelPosition = 'bottom' | 'top' | 'left' | 'right'
type Language = 'en' | 'es' | 'fr' | 'de' | 'zh'

interface Settings {
  historyLimit: number
  pollingInterval: number
  launchAtLogin: boolean
  clearOnQuit: boolean
  showInDock: boolean
  hotkey: string
  playSoundOnCopy: boolean
  ignoreDuplicates: boolean
  ignorePasswordManagers: boolean
  ignoredPasteboardTypes: string[] // Custom pasteboard types to ignore
  panelPosition: PanelPosition
  language: Language
  pasteDirectly: boolean
}

// Default pasteboard types to ignore (matches Maccy's approach)
const DEFAULT_IGNORED_TYPES = [
  // Always ignored - transient/confidential types
  'org.nspasteboard.TransientType',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
  // Password managers and secure apps
  'com.agilebits.onepassword',
  'com.typeit4me.clipping',
  'de.petermaurer.TransientPasteboardType',
  'Pasteboard generator type',
  'net.antelle.keeweb'
]

const defaultSettings: Settings = {
  historyLimit: 500,
  pollingInterval: 500,
  launchAtLogin: false,
  clearOnQuit: false,
  showInDock: false,
  hotkey: 'Option+Space',
  playSoundOnCopy: false,
  ignoreDuplicates: true,
  ignorePasswordManagers: true,
  ignoredPasteboardTypes: DEFAULT_IGNORED_TYPES,
  panelPosition: 'bottom',
  language: 'en',
  pasteDirectly: false // Default: copy only (user manually pastes)
}

const store = new Store<{ history: ClipboardItem[], settings: Settings }>({
  defaults: {
    history: [],
    settings: defaultSettings
  }
})

let mainWindow: BrowserWindow | null = null
let settingsWindow: BrowserWindow | null = null
let tray: Tray | null = null
let lastClipboardContent = ''
let clipboardPollInterval: ReturnType<typeof setInterval> | null = null
let previousApp = '' // Store the app that was active before opening clipboard panel

function getSettings(): Settings {
  return store.get('settings') || defaultSettings
}

function getWindowBounds() {
  // Get display where cursor is (for multi-monitor support)
  const cursorPoint = screen.getCursorScreenPoint()
  const display = screen.getDisplayNearestPoint(cursorPoint)
  const { x: displayX, y: displayY, width, height } = display.bounds

  const settings = getSettings()
  const panelSize = 320

  switch (settings.panelPosition) {
    case 'top':
      return { width, height: panelSize, x: displayX, y: displayY }
    case 'left':
      return { width: panelSize, height, x: displayX, y: displayY }
    case 'right':
      return { width: panelSize, height, x: displayX + width - panelSize, y: displayY }
    case 'bottom':
    default:
      return { width, height: panelSize, x: displayX, y: displayY + height - panelSize }
  }
}

function createWindow() {
  const bounds = getWindowBounds()

  mainWindow = new BrowserWindow({
    ...bounds,
    frame: false,
    transparent: true,
    vibrancy: 'under-window',
    visualEffectState: 'active',
    alwaysOnTop: true,
    skipTaskbar: true,
    resizable: false,
    show: false,
    webPreferences: {
      preload: join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false
    }
  })

  const url = process.env.VITE_DEV_SERVER_URL
  if (url) {
    console.log('Loading dev URL:', url)
    mainWindow.loadURL(url)
    mainWindow.webContents.openDevTools({ mode: 'detach' })
  } else {
    mainWindow.loadFile(join(__dirname, '../dist/index.html'))
  }

  mainWindow.webContents.on('did-finish-load', () => {
    console.log('Window content loaded')
  })

  mainWindow.webContents.on('did-fail-load', (_, code, desc) => {
    console.error('Failed to load:', code, desc)
  })

  mainWindow.on('blur', () => {
    if (mainWindow?.isVisible()) {
      mainWindow.hide()
    }
  })
}

function createTray() {
  // Try multiple paths for the tray icon
  const possiblePaths = [
    join(__dirname, '../assets/trayTemplate.png'),  // Dev mode
    join(process.resourcesPath, 'assets/trayTemplate.png'),  // Production (extraResources)
    join(__dirname, 'assets/trayTemplate.png'),  // Alternative
  ]

  let icon = nativeImage.createEmpty()
  for (const iconPath of possiblePaths) {
    console.log('Trying tray icon path:', iconPath)
    const testIcon = nativeImage.createFromPath(iconPath)
    if (!testIcon.isEmpty()) {
      icon = testIcon
      console.log('Loaded tray icon from:', iconPath)
      break
    }
  }

  icon.setTemplateImage(true)

  if (icon.isEmpty()) {
    console.error('Failed to load tray icon from any path, using fallback')
    const fallback = nativeImage.createFromDataURL(
      'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMklEQVQ4T2NkIBMwkqmegXKDGRhggOL/DAwMjMRoHjUAl7cHiw8YRsMRNkcPltBgoCYHAHCbBBHpOpp5AAAAAElFTkSuQmCC'
    )
    fallback.setTemplateImage(true)
    tray = new Tray(fallback)
  } else {
    tray = new Tray(icon)
  }
  tray.setToolTip('SimpleMacClipboardManager')

  updateTrayMenu()
  tray.on('click', toggleWindow)

  console.log('Tray icon created')
}

function updateTrayMenu() {
  if (!tray) return

  const menu = Menu.buildFromTemplate([
    { label: 'Show Clipboard (⌥Space)', click: () => toggleWindow() },
    { type: 'separator' },
    { label: 'Settings...', click: () => openSettings() },
    { label: 'How to Use...', click: () => showHelp() },
    { label: 'About...', click: () => showAbout() },
    { type: 'separator' },
    { label: 'Clear History', click: () => clearHistory() },
    { type: 'separator' },
    { label: 'Quit', click: () => app.quit() }
  ])

  tray.setContextMenu(menu)
}

function openSettings() {
  if (settingsWindow) {
    settingsWindow.focus()
    return
  }

  settingsWindow = new BrowserWindow({
    width: 480,
    height: 700,
    title: 'Settings',
    resizable: false,
    minimizable: false,
    maximizable: false,
    fullscreenable: false,
    show: false,
    backgroundColor: '#2a2a2a',
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false
    }
  })

  const url = process.env.VITE_DEV_SERVER_URL
  if (url) {
    settingsWindow.loadURL(url + '#settings')
  } else {
    settingsWindow.loadFile(join(__dirname, '../dist/index.html'), { hash: 'settings' })
  }

  settingsWindow.once('ready-to-show', () => {
    settingsWindow?.show()
  })

  settingsWindow.on('closed', () => {
    settingsWindow = null
  })
}

function toggleWindow() {
  if (!mainWindow) return

  if (mainWindow.isVisible()) {
    mainWindow.hide()
  } else {
    // Remember which app was active before opening the panel
    try {
      const script = 'tell application "System Events" to get name of first application process whose frontmost is true'
      previousApp = execSync(`osascript -e '${script}'`, { encoding: 'utf8', timeout: 500 }).trim()
      console.log('Previous app:', previousApp)
    } catch (e) {
      previousApp = ''
    }

    const bounds = getWindowBounds()
    mainWindow.setBounds(bounds)
    mainWindow.show()
    mainWindow.focus()
    mainWindow.webContents.send('panel-shown')
  }
}

function clearHistory() {
  store.set('history', [])
  mainWindow?.webContents.send('history-updated', [])
}

// Move an item to the top of history (when pasted/copied from our app)
function moveItemToTop(id: string) {
  const history = store.get('history')
  const itemIndex = history.findIndex(h => h.id === id)
  if (itemIndex > 0) {
    const item = history[itemIndex]
    item.createdAt = Date.now() // Update timestamp
    const updated = [item, ...history.filter(h => h.id !== id)]
    // Re-sort: pinned items first, then by createdAt
    updated.sort((a, b) => {
      if (a.pinned && !b.pinned) return -1
      if (!a.pinned && b.pinned) return 1
      return b.createdAt - a.createdAt
    })
    store.set('history', updated)
    mainWindow?.webContents.send('history-updated', updated)
  }
}

function showHelp() {
  const iconPath = app.isPackaged
    ? join(process.resourcesPath, 'assets', 'logo.jpg')
    : join(__dirname, '..', 'assets', 'logo.jpg')

  dialog.showMessageBox({
    type: 'info',
    icon: nativeImage.createFromPath(iconPath),
    title: 'How to Use',
    message: 'SimpleMacClipboardManager',
    detail: `Keyboard Shortcuts:
• ⌥Space - Open/close clipboard panel
• ←→ or ↑↓ - Navigate between items
• Enter - Copy to clipboard (or paste if enabled)
• ⌘C - Copy to clipboard (always)
• ⇧Enter - Paste directly as plain text
• Space - Quick Look preview
• ⌘1-9 - Quick paste items 1-9
• ⌘⌫ - Delete selected item
• Esc - Close panel

Mouse Actions:
• Click - Select item
• Double-click - Copy (or paste if enabled)
• Right-click - Copy (or paste if enabled)
• Star icon - Pin/unpin item

Tips:
• Type to search clipboard history
• Use filter buttons to show specific types
• Pinned items stay at the top
• Enable "Paste directly" in Settings to auto-paste`,
    buttons: ['OK']
  })
}

function showAbout() {
  const iconPath = app.isPackaged
    ? join(process.resourcesPath, 'assets', 'logo.jpg')
    : join(__dirname, '..', 'assets', 'logo.jpg')

  const version = app.getVersion()

  dialog.showMessageBox({
    type: 'info',
    icon: nativeImage.createFromPath(iconPath),
    title: 'About',
    message: 'SimpleMacClipboardManager',
    detail: `Version ${version}

A free, lightweight clipboard manager for macOS.
Keep your clipboard history organized and accessible.

Created by @robbyczgw-cla`,
    buttons: ['GitHub Repo', 'Author Profile', 'OK'],
    defaultId: 2,
    cancelId: 2
  }).then(result => {
    if (result.response === 0) {
      shell.openExternal('https://github.com/robbyczgw-cla/SimpleMacClipboardManager')
    } else if (result.response === 1) {
      shell.openExternal('https://github.com/robbyczgw-cla')
    }
  })
}

function detectContentType(text: string): ClipboardItem['type'] {
  const trimmed = text.trim()
  if (/^#([0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$/.test(trimmed)) return 'color'
  if (/^https?:\/\/\S+$/.test(trimmed)) return 'link'
  if (/^(\/|~\/|[A-Z]:\\)/.test(trimmed)) return 'file'
  return 'text'
}

// Get favicon URL for a domain using Google's service
function getFaviconUrl(url: string): string {
  try {
    const domain = new URL(url).hostname
    return `https://www.google.com/s2/favicons?domain=${domain}&sz=32`
  } catch {
    return ''
  }
}

// Password manager app identifiers (backup check by app name)
const PASSWORD_MANAGER_APPS = [
  '1password', 'onepassword', 'bitwarden', 'lastpass', 'dashlane',
  'keeper', 'keychain', 'enpass', 'roboform', 'nordpass', 'proton pass'
]

function getFrontmostApp(): string {
  try {
    const script = 'tell application "System Events" to get name of first application process whose frontmost is true'
    const result = execSync(`osascript -e '${script}'`, { encoding: 'utf8', timeout: 500 })
    return result.trim().toLowerCase()
  } catch {
    return ''
  }
}

// Check if clipboard contains ignored pasteboard types (Maccy-style)
function hasIgnoredPasteboardType(): boolean {
  const settings = getSettings()
  const ignoredTypes = settings.ignoredPasteboardTypes || DEFAULT_IGNORED_TYPES

  try {
    const formats = clipboard.availableFormats()
    return formats.some(format =>
      ignoredTypes.some(ignored =>
        format.toLowerCase().includes(ignored.toLowerCase())
      )
    )
  } catch {
    return false
  }
}

function isPasswordManagerActive(): boolean {
  // First check pasteboard types (more reliable)
  if (hasIgnoredPasteboardType()) {
    return true
  }
  // Fallback to app name check
  const frontApp = getFrontmostApp()
  return PASSWORD_MANAGER_APPS.some(pm => frontApp.includes(pm))
}

function startClipboardPolling() {
  const settings = getSettings()

  if (clipboardPollInterval) {
    clearInterval(clipboardPollInterval)
  }

  // Safely read initial clipboard content
  try {
    lastClipboardContent = clipboard.readText() || ''
  } catch (e) {
    console.error('Failed to read initial clipboard:', e)
    lastClipboardContent = ''
  }

  clipboardPollInterval = setInterval(pollClipboard, settings.pollingInterval)
  console.log('Clipboard polling started with interval:', settings.pollingInterval)
}

let lastImageDataUrl = ''

function pollClipboard() {
  try {
    const settings = getSettings()
    const text = clipboard.readText()
    const image = clipboard.readImage()

    // Check for image first
    if (!image.isEmpty()) {
      const imageDataUrl = image.toDataURL()

      // Check if this is a new image (not the same as last one)
      if (imageDataUrl !== lastImageDataUrl && imageDataUrl.length > 100) {
        lastImageDataUrl = imageDataUrl

        // Check if we should ignore password managers
        if (settings.ignorePasswordManagers && isPasswordManagerActive()) {
          return
        }

        const history = store.get('history')
        const sourceApp = getFrontmostApp()

        // Create compressed thumbnail (smaller size, JPEG quality 70%)
        const resized = image.resize({ width: 120, height: 120 })
        const thumbnail = resized.toJPEG(70).toString('base64')
        const thumbnailDataUrl = `data:image/jpeg;base64,${thumbnail}`

        const item: ClipboardItem = {
          id: uuidv4(),
          type: 'image',
          content: imageDataUrl,
          thumbnail: thumbnailDataUrl,
          metadata: {
            sourceApp: sourceApp || undefined
          },
          createdAt: Date.now(),
          searchText: 'image screenshot',
          pinned: false
        }

        const updated = [item, ...history].slice(0, settings.historyLimit)
        store.set('history', updated)
        mainWindow?.webContents.send('history-updated', updated)
        return
      }
    }

    // Check for text
    if (text && text !== lastClipboardContent) {
      // Check if we should ignore password managers
      if (settings.ignorePasswordManagers && isPasswordManagerActive()) {
        console.log('Ignored clipboard from password manager')
        lastClipboardContent = text
        return
      }

      // Check for duplicates (consecutive identical copies)
      const history = store.get('history')
      if (settings.ignoreDuplicates && history.length > 0 && history[0].content === text) {
        lastClipboardContent = text
        return
      }

      lastClipboardContent = text
      lastImageDataUrl = '' // Clear image when text is copied
      const type = detectContentType(text)
      const sourceApp = getFrontmostApp()

      // Truncate searchText for very long content (keeps search fast)
      const MAX_SEARCH_TEXT = 5000
      const searchText = text.length > MAX_SEARCH_TEXT
        ? text.slice(0, MAX_SEARCH_TEXT).toLowerCase()
        : text.toLowerCase()

      const item: ClipboardItem = {
        id: uuidv4(),
        type,
        content: text, // Full content preserved for pasting
        metadata: {
          url: type === 'link' ? text : undefined,
          colorHex: type === 'color' ? text : undefined,
          sourceApp: sourceApp || undefined,
          favicon: type === 'link' ? getFaviconUrl(text) : undefined
        },
        createdAt: Date.now(),
        searchText,
        pinned: false
      }

      const filtered = history.filter(h => h.content !== text)
      const updated = [item, ...filtered].slice(0, settings.historyLimit)
      store.set('history', updated)
      mainWindow?.webContents.send('history-updated', updated)
    }
  } catch (e) {
    console.error('Clipboard poll error:', e)
    // Continue polling despite error
  }
}

function applySettings(settings: Settings) {
  // Apply launch at login
  app.setLoginItemSettings({
    openAtLogin: settings.launchAtLogin,
    openAsHidden: true
  })

  // Apply dock visibility
  if (settings.showInDock) {
    app.dock?.show()
  } else {
    app.dock?.hide()
  }

  // Restart polling with new interval
  startClipboardPolling()

  // Re-register hotkey if changed
  globalShortcut.unregisterAll()
  const hotkeyRegistered = globalShortcut.register(settings.hotkey, toggleWindow)
  console.log('Hotkey re-registered:', settings.hotkey, hotkeyRegistered)

  // Update window position if panel position changed
  if (mainWindow && !mainWindow.isVisible()) {
    const bounds = getWindowBounds()
    mainWindow.setBounds(bounds)
  }
}

app.whenReady().then(() => {
  console.log('App ready, creating window and tray...')

  // Check accessibility permissions (required for global hotkeys)
  if (process.platform === 'darwin') {
    const isTrusted = systemPreferences.isTrustedAccessibilityClient({ prompt: false })
    console.log('Accessibility permission:', isTrusted ? 'granted' : 'not granted')

    if (!isTrusted) {
      // Prompt user for accessibility permission
      const result = dialog.showMessageBoxSync({
        type: 'info',
        title: 'Accessibility Permission Required',
        message: 'SimpleMacClipboardManager needs Accessibility permission to use global hotkeys.',
        detail: 'Click "Open System Preferences" to grant permission, then restart the app.',
        buttons: ['Open System Preferences', 'Later']
      })

      if (result === 0) {
        // This will open System Preferences and prompt for permission
        systemPreferences.isTrustedAccessibilityClient({ prompt: true })
      }
    }
  }

  const settings = getSettings()

  // Apply initial settings
  if (!settings.showInDock) {
    app.dock?.hide()
  }

  app.setLoginItemSettings({
    openAtLogin: settings.launchAtLogin,
    openAsHidden: true
  })

  createWindow()
  createTray()
  startClipboardPolling()

  // Register hotkey
  const registered = globalShortcut.register(settings.hotkey, toggleWindow)
  console.log('Hotkey registered:', registered)

  // IPC handlers
  ipcMain.handle('get-history', () => store.get('history'))

  ipcMain.handle('paste-item', (_, item: ClipboardItem) => {
    if (item.type === 'image' && item.content.startsWith('data:')) {
      // For images, write the image to clipboard
      const image = nativeImage.createFromDataURL(item.content)
      clipboard.writeImage(image)
    } else {
      clipboard.writeText(item.content)
    }
    lastClipboardContent = item.content
    lastImageDataUrl = item.type === 'image' ? item.content : ''

    // Move item to top of history (update timestamp)
    moveItemToTop(item.id)

    mainWindow?.hide()

    // Activate the previous app and simulate Cmd+V
    setTimeout(() => {
      try {
        if (previousApp) {
          // Activate the previous app first, then paste
          execSync(`osascript -e 'tell application "${previousApp}" to activate' -e 'delay 0.1' -e 'tell application "System Events" to keystroke "v" using command down'`)
        }
      } catch (e) {
        console.error('Failed to simulate paste:', e)
      }
    }, 100)
  })

  ipcMain.handle('paste-plain', (_, item: ClipboardItem) => {
    // Always paste as plain text, stripping any formatting
    const plainText = item.type === 'image' ? '[Image]' : item.content.replace(/<[^>]*>/g, '')
    clipboard.writeText(plainText)
    lastClipboardContent = plainText

    // Move item to top of history (update timestamp)
    moveItemToTop(item.id)

    mainWindow?.hide()

    // Activate the previous app and simulate Cmd+V
    setTimeout(() => {
      try {
        if (previousApp) {
          execSync(`osascript -e 'tell application "${previousApp}" to activate' -e 'delay 0.1' -e 'tell application "System Events" to keystroke "v" using command down'`)
        }
      } catch (e) {
        console.error('Failed to simulate paste:', e)
      }
    }, 100)
  })

  ipcMain.handle('copy-only', (_, item: ClipboardItem) => {
    // Copy to clipboard without auto-pasting
    if (item.type === 'image' && item.content.startsWith('data:')) {
      const image = nativeImage.createFromDataURL(item.content)
      clipboard.writeImage(image)
    } else {
      clipboard.writeText(item.content)
    }
    lastClipboardContent = item.content
    lastImageDataUrl = item.type === 'image' ? item.content : ''

    // Move item to top of history (update timestamp)
    moveItemToTop(item.id)

    mainWindow?.hide()
    // No auto-paste - user will manually Cmd+V
  })

  ipcMain.handle('delete-item', (_, id: string) => {
    const history = store.get('history').filter(h => h.id !== id)
    store.set('history', history)
    mainWindow?.webContents.send('history-updated', history)
  })

  ipcMain.handle('toggle-pin', (_, id: string) => {
    const history = store.get('history').map(h =>
      h.id === id ? { ...h, pinned: !h.pinned } : h
    )
    // Sort: pinned items first, then by createdAt
    history.sort((a, b) => {
      if (a.pinned && !b.pinned) return -1
      if (!a.pinned && b.pinned) return 1
      return b.createdAt - a.createdAt
    })
    store.set('history', history)
    mainWindow?.webContents.send('history-updated', history)
  })

  ipcMain.handle('clear-history', clearHistory)
  ipcMain.handle('hide-window', () => mainWindow?.hide())

  // Settings handlers
  ipcMain.handle('get-settings', () => getSettings())

  ipcMain.handle('save-settings', (_, newSettings: Settings) => {
    store.set('settings', newSettings)
    applySettings(newSettings)
    console.log('Settings saved:', newSettings)
  })

  ipcMain.handle('open-settings', openSettings)

  // Export history as JSON
  ipcMain.handle('export-history', async () => {
    const history = store.get('history')
    const result = await dialog.showSaveDialog({
      title: 'Export Clipboard History',
      defaultPath: `clipboard-history-${new Date().toISOString().split('T')[0]}.json`,
      filters: [{ name: 'JSON', extensions: ['json'] }]
    })

    if (!result.canceled && result.filePath) {
      const fs = await import('fs')
      fs.writeFileSync(result.filePath, JSON.stringify(history, null, 2))
      return { success: true, path: result.filePath }
    }
    return { success: false }
  })

  // Import history from JSON
  ipcMain.handle('import-history', async () => {
    const result = await dialog.showOpenDialog({
      title: 'Import Clipboard History',
      filters: [{ name: 'JSON', extensions: ['json'] }],
      properties: ['openFile']
    })

    if (!result.canceled && result.filePaths.length > 0) {
      try {
        const fs = await import('fs')
        const data = fs.readFileSync(result.filePaths[0], 'utf8')
        const imported = JSON.parse(data) as ClipboardItem[]
        const settings = getSettings()

        // Merge with existing history, avoiding duplicates by content
        const existing = store.get('history')
        const existingContents = new Set(existing.map(h => h.content))
        const newItems = imported.filter(item => !existingContents.has(item.content))

        const merged = [...existing, ...newItems].slice(0, settings.historyLimit)
        // Sort: pinned first, then by date
        merged.sort((a, b) => {
          if (a.pinned && !b.pinned) return -1
          if (!a.pinned && b.pinned) return 1
          return b.createdAt - a.createdAt
        })

        store.set('history', merged)
        mainWindow?.webContents.send('history-updated', merged)
        return { success: true, count: newItems.length }
      } catch (e) {
        return { success: false, error: 'Invalid JSON file' }
      }
    }
    return { success: false }
  })

  console.log('All handlers registered')
})

app.on('will-quit', () => {
  const settings = getSettings()

  // Clear history on quit if enabled
  if (settings.clearOnQuit) {
    store.set('history', [])
    console.log('History cleared on quit')
  }

  globalShortcut.unregisterAll()
  if (clipboardPollInterval) clearInterval(clipboardPollInterval)
})

app.on('window-all-closed', (e: Event) => {
  e.preventDefault() // Keep app running
})
