import { useState, useEffect } from 'react'
import { getTranslations, languageNames, Language } from '../i18n/translations'

type PanelPosition = 'bottom' | 'top' | 'left' | 'right'
type CardSize = 'small' | 'medium' | 'large'

interface Settings {
  historyLimit: number
  pollingInterval: number
  launchAtLogin: boolean
  clearOnQuit: boolean
  showInDock: boolean
  hotkey: string
  playSoundOnCopy: boolean
  ignoreDuplicates: boolean
  ignorePasswordManagers: boolean
  ignoredPasteboardTypes: string[]
  panelPosition: PanelPosition
  language: Language
  pasteDirectly: boolean
  cardSize: CardSize
}

const DEFAULT_IGNORED_TYPES = [
  'org.nspasteboard.TransientType',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
  'com.agilebits.onepassword',
  'com.typeit4me.clipping',
  'de.petermaurer.TransientPasteboardType',
  'Pasteboard generator type',
  'net.antelle.keeweb'
]

const defaultSettings: Settings = {
  historyLimit: 500,
  pollingInterval: 500,
  launchAtLogin: false,
  clearOnQuit: false,
  showInDock: false,
  hotkey: 'Option+Space',
  playSoundOnCopy: false,
  ignoreDuplicates: true,
  ignorePasswordManagers: true,
  ignoredPasteboardTypes: DEFAULT_IGNORED_TYPES,
  panelPosition: 'bottom',
  language: 'en',
  pasteDirectly: false,
  cardSize: 'medium'
}

export default function SettingsPage() {
  const [settings, setSettings] = useState<Settings>(defaultSettings)
  const [saved, setSaved] = useState(false)

  useEffect(() => {
    window.electronAPI.getSettings().then(setSettings)
  }, [])

  const t = getTranslations(settings.language)

  const handleSave = async () => {
    await window.electronAPI.saveSettings(settings)
    setSaved(true)
    setTimeout(() => setSaved(false), 2000)
  }

  const handleChange = <K extends keyof Settings>(key: K, value: Settings[K]) => {
    setSettings(prev => ({ ...prev, [key]: value }))
  }

  return (
    <div className="h-full bg-[#2a2a2a] text-white p-6 pt-10 flex flex-col">
      {/* Drag region for title bar */}
      <div className="absolute top-0 left-0 right-0 h-8 app-drag" />

      <h1 className="text-xl font-semibold mb-6">{t.settings}</h1>

      <div className="space-y-6 flex-1 overflow-y-auto pr-2">
        {/* History Section */}
        <section className="bg-white/5 rounded-lg p-4">
          <h3 className="text-sm font-medium text-white/80 mb-4">{t.history}</h3>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <label className="text-sm text-white/70">{t.maximumItems}</label>
              <select
                value={settings.historyLimit}
                onChange={e => handleChange('historyLimit', Number(e.target.value))}
                className="bg-white/10 border border-white/10 rounded px-3 py-1.5 text-sm text-white focus:outline-none focus:border-blue-500"
              >
                <option value={100}>100</option>
                <option value={250}>250</option>
                <option value={500}>500</option>
                <option value={1000}>1000</option>
                <option value={2000}>2000</option>
              </select>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">{t.ignoreDuplicates}</label>
                <p className="text-xs text-white/40">{t.ignoreDuplicatesDesc}</p>
              </div>
              <input
                type="checkbox"
                checked={settings.ignoreDuplicates}
                onChange={e => handleChange('ignoreDuplicates', e.target.checked)}
                className="w-4 h-4 rounded accent-blue-500"
              />
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">{t.clearOnQuit}</label>
                <p className="text-xs text-white/40">{t.clearOnQuitDesc}</p>
              </div>
              <input
                type="checkbox"
                checked={settings.clearOnQuit}
                onChange={e => handleChange('clearOnQuit', e.target.checked)}
                className="w-4 h-4 rounded accent-blue-500"
              />
            </div>
          </div>
        </section>

        {/* Behavior Section */}
        <section className="bg-white/5 rounded-lg p-4">
          <h3 className="text-sm font-medium text-white/80 mb-4">{t.behavior}</h3>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <label className="text-sm text-white/70">{t.pollingInterval}</label>
              <select
                value={settings.pollingInterval}
                onChange={e => handleChange('pollingInterval', Number(e.target.value))}
                className="bg-white/10 border border-white/10 rounded px-3 py-1.5 text-sm text-white focus:outline-none focus:border-blue-500"
              >
                <option value={250}>250ms ({t.fast})</option>
                <option value={500}>500ms ({t.default})</option>
                <option value={1000}>1000ms ({t.slow})</option>
              </select>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">{t.launchAtLogin}</label>
                <p className="text-xs text-white/40">{t.launchAtLoginDesc}</p>
              </div>
              <input
                type="checkbox"
                checked={settings.launchAtLogin}
                onChange={e => handleChange('launchAtLogin', e.target.checked)}
                className="w-4 h-4 rounded accent-blue-500"
              />
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">{t.showInDock}</label>
                <p className="text-xs text-white/40">{t.showInDockDesc}</p>
              </div>
              <input
                type="checkbox"
                checked={settings.showInDock}
                onChange={e => handleChange('showInDock', e.target.checked)}
                className="w-4 h-4 rounded accent-blue-500"
              />
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">{t.playSoundOnCopy}</label>
                <p className="text-xs text-white/40">{t.playSoundOnCopyDesc}</p>
              </div>
              <input
                type="checkbox"
                checked={settings.playSoundOnCopy}
                onChange={e => handleChange('playSoundOnCopy', e.target.checked)}
                className="w-4 h-4 rounded accent-blue-500"
              />
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">Paste directly</label>
                <p className="text-xs text-white/40">Auto-paste when selecting (off = copy only)</p>
              </div>
              <input
                type="checkbox"
                checked={settings.pasteDirectly}
                onChange={e => handleChange('pasteDirectly', e.target.checked)}
                className="w-4 h-4 rounded accent-blue-500"
              />
            </div>
          </div>
        </section>

        {/* Privacy Section */}
        <section className="bg-white/5 rounded-lg p-4">
          <h3 className="text-sm font-medium text-white/80 mb-4">{t.privacy}</h3>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">{t.ignorePasswordManagers}</label>
                <p className="text-xs text-white/40">{t.ignorePasswordManagersDesc}</p>
              </div>
              <input
                type="checkbox"
                checked={settings.ignorePasswordManagers}
                onChange={e => handleChange('ignorePasswordManagers', e.target.checked)}
                className="w-4 h-4 rounded accent-blue-500"
              />
            </div>
            {settings.ignorePasswordManagers && (
              <div>
                <label className="text-sm text-white/70">Ignored pasteboard types</label>
                <p className="text-xs text-white/40 mb-2">One type per line. Matches Maccy defaults.</p>
                <textarea
                  value={(settings.ignoredPasteboardTypes || DEFAULT_IGNORED_TYPES).join('\n')}
                  onChange={e => handleChange('ignoredPasteboardTypes', e.target.value.split('\n').filter(t => t.trim()))}
                  className="w-full h-32 bg-white/10 border border-white/10 rounded px-3 py-2 text-xs text-white font-mono focus:outline-none focus:border-blue-500 resize-none"
                  placeholder="org.nspasteboard.TransientType"
                />
                <button
                  onClick={() => handleChange('ignoredPasteboardTypes', DEFAULT_IGNORED_TYPES)}
                  className="mt-2 text-xs text-blue-400 hover:text-blue-300"
                >
                  Reset to defaults
                </button>
              </div>
            )}
          </div>
        </section>

        {/* Appearance Section */}
        <section className="bg-white/5 rounded-lg p-4">
          <h3 className="text-sm font-medium text-white/80 mb-4">{t.appearance}</h3>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">{t.panelPosition}</label>
                <p className="text-xs text-white/40">{t.panelPositionDesc}</p>
              </div>
              <select
                value={settings.panelPosition}
                onChange={e => handleChange('panelPosition', e.target.value as PanelPosition)}
                className="bg-white/10 border border-white/10 rounded px-3 py-1.5 text-sm text-white focus:outline-none focus:border-blue-500"
              >
                <option value="bottom">{t.bottom}</option>
                <option value="top">{t.top}</option>
                <option value="left">{t.left}</option>
                <option value="right">{t.right}</option>
              </select>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">{t.language}</label>
                <p className="text-xs text-white/40">{t.languageDesc}</p>
              </div>
              <select
                value={settings.language}
                onChange={e => handleChange('language', e.target.value as Language)}
                className="bg-white/10 border border-white/10 rounded px-3 py-1.5 text-sm text-white focus:outline-none focus:border-blue-500"
              >
                {(Object.keys(languageNames) as Language[]).map(lang => (
                  <option key={lang} value={lang}>{languageNames[lang]}</option>
                ))}
              </select>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">Card Size</label>
                <p className="text-xs text-white/40">Size of clipboard item cards</p>
              </div>
              <select
                value={settings.cardSize || 'medium'}
                onChange={e => handleChange('cardSize', e.target.value as CardSize)}
                className="bg-white/10 border border-white/10 rounded px-3 py-1.5 text-sm text-white focus:outline-none focus:border-blue-500"
              >
                <option value="small">Small</option>
                <option value="medium">Medium</option>
                <option value="large">Large</option>
              </select>
            </div>
          </div>
        </section>

        {/* Keyboard Section */}
        <section className="bg-white/5 rounded-lg p-4">
          <h3 className="text-sm font-medium text-white/80 mb-4">{t.keyboard}</h3>
          <div className="flex items-center justify-between">
            <label className="text-sm text-white/70">{t.globalHotkey}</label>
            <select
              value={settings.hotkey}
              onChange={e => handleChange('hotkey', e.target.value)}
              className="bg-white/10 border border-white/10 rounded px-3 py-1.5 text-sm text-white focus:outline-none focus:border-blue-500"
            >
              <option value="Option+Space">⌥Space</option>
              <option value="CommandOrControl+Shift+V">⌘⇧V</option>
              <option value="CommandOrControl+Shift+C">⌘⇧C</option>
              <option value="CommandOrControl+Shift+H">⌘⇧H</option>
              <option value="CommandOrControl+Option+V">⌘⌥V</option>
              <option value="CommandOrControl+Option+C">⌘⌥C</option>
              <option value="CommandOrControl+Option+H">⌘⌥H</option>
              <option value="CommandOrControl+Option+P">⌘⌥P</option>
            </select>
          </div>
          <p className="text-xs text-white/40 mt-2">
            {t.restartHotkey}
          </p>
        </section>

        {/* Backup Section */}
        <section className="bg-white/5 rounded-lg p-4">
          <h3 className="text-sm font-medium text-white/80 mb-4">Backup</h3>
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">Export History</label>
                <p className="text-xs text-white/40">Save clipboard history as JSON file</p>
              </div>
              <button
                onClick={async () => {
                  const result = await window.electronAPI.exportHistory()
                  if (result.success) {
                    setSaved(true)
                    setTimeout(() => setSaved(false), 2000)
                  }
                }}
                className="px-3 py-1.5 text-sm bg-white/10 hover:bg-white/20 text-white rounded transition-colors"
              >
                Export
              </button>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <label className="text-sm text-white/70">Import History</label>
                <p className="text-xs text-white/40">Load clipboard history from JSON file</p>
              </div>
              <button
                onClick={async () => {
                  const result = await window.electronAPI.importHistory()
                  if (result.success) {
                    setSaved(true)
                    setTimeout(() => setSaved(false), 2000)
                  }
                }}
                className="px-3 py-1.5 text-sm bg-white/10 hover:bg-white/20 text-white rounded transition-colors"
              >
                Import
              </button>
            </div>
          </div>
        </section>
      </div>

      {/* Save Button */}
      <div className="mt-6 flex items-center justify-between">
        <span className={`text-sm transition-opacity ${saved ? 'text-green-400 opacity-100' : 'opacity-0'}`}>
          ✓ {t.settingsSaved}
        </span>
        <button
          onClick={handleSave}
          className="px-5 py-2 text-sm bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition-colors"
        >
          {t.saveSettings}
        </button>
      </div>
    </div>
  )
}
