import type { Settings } from './types'

// Single source of truth for default settings, shared by the main process
// (electron/main.ts) and the renderer (SettingsPage). Keep this the ONLY place
// these defaults live so the two processes never disagree.

// Default pasteboard types to ignore (matches Maccy's approach).
export const DEFAULT_IGNORED_TYPES = [
  // Always ignored - transient/confidential types
  'org.nspasteboard.TransientType',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType',
  // Password managers and secure apps
  'com.agilebits.onepassword',
  'com.typeit4me.clipping',
  'de.petermaurer.TransientPasteboardType',
  'Pasteboard generator type',
  'net.antelle.keeweb'
]

// These pasteboard markers are always treated as sensitive/transient. The
// user-facing password-manager toggle must not disable these safeguards.
export const ALWAYS_IGNORED_TYPES = [
  'org.nspasteboard.TransientType',
  'org.nspasteboard.ConcealedType',
  'org.nspasteboard.AutoGeneratedType'
]

export const defaultSettings: Settings = {
  historyLimit: 500,
  pollingInterval: 500,
  launchAtLogin: false,
  clearOnQuit: false,
  showInDock: false,
  hotkey: 'Option+Space',
  playSoundOnCopy: false,
  ignoreDuplicates: true,
  ignorePasswordManagers: true,
  ignoredPasteboardTypes: DEFAULT_IGNORED_TYPES,
  panelPosition: 'bottom',
  language: 'en',
  pasteDirectly: false, // Default: copy only (user manually pastes)
  cardSize: 'medium',
  loadFavicons: false,
  // 8MB default; images larger than this will be downscaled before persisting.
  maxImageBytes: 8 * 1024 * 1024,
  retentionDays: 0,
  ignoredApplications: [],
  onboardingCompleted: false
}

// Bounds used to sanitize untrusted settings (from the UI or an import) before
// they reach the polling loop / storage.
export const SETTINGS_BOUNDS = {
  pollingIntervalMin: 100,
  pollingIntervalMax: 5000,
  historyLimitMin: 1,
  historyLimitMax: 5000,
  maxImageBytesMin: 512 * 1024,
  maxImageBytesMax: 64 * 1024 * 1024
}
